#!/bin/bash

gh repo list | while read -r repo _; do
  DEST_DIR="$1"/$(basename "$repo")
  echo "Cloning $repo to $DEST_DIR"

  gh repo clone "$repo" "$1"/$(basename "$repo") 2>/dev/null|| (
    cd "$DEST_DIR"
    # Handle case where local checkout is on a non-main/master branch
    # - ignore checkout errors because some repos may have zero commits,
    # so no main or master
    git checkout main 2>/dev/null || true
    git checkout master 2>/dev/null || true
    git pull
  )
done
