#!/bin/bash
# v0.3

DATETIME=$(date +"%Y_%m_%d__%H_%M_%S")

read_args() {
    num2keep=10
    if (( $# > 1 )); then
        num2keep=$2
    fi
}

prune() {
    if (( $(zfs list -t snapshot | grep $1 | wc -l) > $num2keep))
    then
        zfs list -t snapshot | grep $1 | awk '{print $1}' | head -n -$num2keep | xargs -I snap zfs destroy snap
    fi
}

snapshot() {
    snapname="snap_$DATETIME"
    zfs snapshot $1@$snapname
}

read_args
snapshot
prune
